"""empty message

Revision ID: c3aa7db18781
Revises: 886684006b8b
Create Date: 2017-09-18 12:36:12.592000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3aa7db18781'
down_revision = '886684006b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animes', sa.Column('genres', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animes', 'genres')
    # ### end Alembic commands ###
