"""empty message

Revision ID: 886684006b8b
Revises: d08712a23185
Create Date: 2017-09-18 12:35:14.714000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '886684006b8b'
down_revision = 'd08712a23185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animes', 'genres')
    op.add_column('genres', sa.Column('anime_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'genres', 'animes', ['anime_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'genres', type_='foreignkey')
    op.drop_column('genres', 'anime_id')
    op.add_column('animes', sa.Column('genres', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
