"""empty message

Revision ID: cf8b86182eb8
Revises: c3aa7db18781
Create Date: 2017-09-18 12:39:49.319000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf8b86182eb8'
down_revision = 'c3aa7db18781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animes', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animes', sa.Column('genres', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
